# If you have any problem about this theme, 
# please let me kown it via email or GitHub issue.
# Thanks!

# first_screen
## the links part of first screen: you can add any link, just like <GitHub: [your github url]>
first_screen:
  img: #https://ws3.sinaimg.cn/large/006tNc79gy1fiyf9ncv1tj31kw11odmz.jpg
  gradient:
    left: '#3a6186'
    right: '#89253e'
  name: Poem ## the largest word on the first screen
  description: Life is a Poem ## The description of your site
  links: 

# header
## the links part of header supports: 
## email, weibo, twitter, github, gitlab, facebook, dribbble, behance
header:
  logo: https://ws1.sinaimg.cn/large/006tNc79gy1fiwje9t48fj30ro0rojss.jpg ## the logo on the header
  description: Codpoe / Front-End Developer ##
  links:
    email: codpoe.me@gmail.com
    weibo: http://weibo.cn
    github: https://github.com

  menu: ## the menu on the header, you can customize it.
    home: /
    category: /categories
    archive: /archives
    about: /about

# footer
copyright: 
  time: 2017 ## the time of copyright in the footer
  name: Poem ## the name of copyright in the footer

# disqus
## you can find more help on https://disqus.com/.
disqus:
  open: false ## toggle whether your site open the disqus
  shortname: ## your disqus shortname

