# If you have any problem about this theme, 
# please let me kown it via email or GitHub issue.
# Thanks!

# first_screen
## the links part of first screen: you can add any link, just like <GitHub: [your github url]>
first_screen:
  open: true ## toggle whether your site shows the first screen
  name: Poem ## the largest word on the first screen
  description: Life is a Poem ## The description of your site
  links: 

# header
## the links part of header supports: 
## email, weibo, twitter, github, gitlab, facebook, dribbble, behance
header:
  logo: ## the logo on the header
  links: 

  menu: ## the menu on the header, you can customize it.
    home: /
    category: /categories/
    archive: /archives/
    about: /about/

# footer
copyright: 
  time: 2017 ## the time of copyright in the footer
  name: Poem ## the name of copyright in the footer

# triangle_canvas
triangle_canvas: true ## toggle whether your site show the colorful triangle-canvas in the top of all page

# disqus
## you can find more help on https://disqus.com/.
disqus:
  open: false ## toggle whether your site open the disqus
  shortname: ## your disqus shortname

